<a href="https://colab.research.google.com/github/mindchu/01276551-INTRO-TO-DATA-ANALYTICS/blob/main/quiz/pandas_quiz_ep2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#@title Your Information

full_name =  'Chuthathip Termchaikul' #@param {type:"string"}
student_id =  '67011594'  #@param {type:"string"}

#@markdown ---

# **Pandas Quiz Ep.2**
> ## *Author* : [Rathachai CHAWUTHAI](https://rathachai.creatier.pro/) , Ph.D
> ### *Affiliation* : Computer Engineering, King Mongkut's Institute of Technology Ladkrabang (KMITL)
> #### *Updated Date* : 2022-03-23
---

## Instruction

Write Python code to answer each question. In general, it uses 1 line of code for each answer.

## คำสั่ง

จงเขียนโค้ดภาษาไพธอนเพื่อตอบคำถาม
ซึ่งโดยทั่วไปคำตอบแต่ละข้อจะใช้เพียง 1 บรรทัดโค้ด

## Q0

Import nessessary Libraries

นำเข้า libraries ที่จำเป็น

In [2]:
import pandas as pd

## Q1

Read data from
https://docs.google.com/spreadsheets/d/e/2PACX-1vRIFbIywXecgxN5c1sMn_KYWsARoXgp4paFxu4qndPaX_47vRaOdrqmiHjtNZ9ZYQcv3ubMSv8DA9ta/pub?gid=0&single=true&output=csv  

into a dataframe named **df**

จงอ่านข้อมูลจาก sheet จาก link ที่กำหนดเป็น Pandas Dataframe ชื่อ **df**

In [21]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRIFbIywXecgxN5c1sMn_KYWsARoXgp4paFxu4qndPaX_47vRaOdrqmiHjtNZ9ZYQcv3ubMSv8DA9ta/pub?gid=0&single=true&output=csv")

## Q2

List the top-3 tallest people

เลือก 3 คนแรกที่สูงที่สุด

In [22]:
df.sort_values("height", ascending=False).head(3)

,eid,name,gender,department,age,height,weight,gpa,salary,working_years,car_park,birth_place
7,E018,Harit,male,devops,32,180,67.5,3.45,67700.0,5,True,Bangkok
1,E012,Bordin,male,developer,25,179,78.4,2.39,48700.0,2,True,Phuket
4,E015,Ekkasit,male,marketing,37,177,66.4,3.33,80500.0,7,True,Suphanburi

## Q3

The metric BMI formula = Weight (kg) ÷ Height (Metres)².
Create a new columns named "bmi" with the bmi value


คำนวณค่า BMI จากสมการ นำ้หนัก (kg) ÷ ส่วนสูง (Metres)²
แล้วสร้างคอลัมน์ใหม่ ชื่อ "bmi" สำหรับค่าที่คำนวณนี้

In [23]:
df["bmi"] = df["weight"] / ((df["height"] / 100) ** 2)
df

,eid,name,gender,department,age,height,weight,gpa,salary,working_years,car_park,birth_place,bmi
0,E011,Anda,female,developer,39,166,53.8,3.02,64200.0,4,True,Bangkok,19.523879
1,E012,Bordin,male,developer,25,179,78.4,2.39,48700.0,2,True,Phuket,24.468650
2,E013,Chantana,female,developer,29,171,70.2,3.02,45500.0,3,False,Chonburi,24.007387
3,E014,Donlaya,female,marketing,39,154,66.5,3.21,72600.0,8,False,Chonburi,28.040142
4,E015,Ekkasit,male,marketing,37,177,66.4,3.33,80500.0,7,True,Suphanburi,21.194421
5,E016,Fundee,female,support,35,156,75.6,2.38,56600.0,3,False,Phuket,31.065089
6,E017,Gitiwit,male,support,26,175,69.7,3.25,42400.0,2,False,Suphanburi,22.759184
7,E018,Harit,male,devops,32,180,67.5,3.45,67700.0,5,True,Bangkok,20.833333

## Q4

Change the salary of Ekkasit by increasing 10%.

จงเพิ่มเงินเดือนของ Ekkasit ขึ้นอีก 10%

In [24]:
df.loc[df["name"] == "Ekkasit", "salary"] *= 1.10
df

,eid,name,gender,department,age,height,weight,gpa,salary,working_years,car_park,birth_place,bmi
0,E011,Anda,female,developer,39,166,53.8,3.02,64200.0,4,True,Bangkok,19.523879
1,E012,Bordin,male,developer,25,179,78.4,2.39,48700.0,2,True,Phuket,24.468650
2,E013,Chantana,female,developer,29,171,70.2,3.02,45500.0,3,False,Chonburi,24.007387
3,E014,Donlaya,female,marketing,39,154,66.5,3.21,72600.0,8,False,Chonburi,28.040142
4,E015,Ekkasit,male,marketing,37,177,66.4,3.33,88550.0,7,True,Suphanburi,21.194421
5,E016,Fundee,female,support,35,156,75.6,2.38,56600.0,3,False,Phuket,31.065089
6,E017,Gitiwit,male,support,26,175,69.7,3.25,42400.0,2,False,Suphanburi,22.759184
7,E018,Harit,male,devops,32,180,67.5,3.45,67700.0,5,True,Bangkok,20.833333

## Q5

In crease the salary of people, who use the car park space (car_park=True) by 1000 THB.

จงเพิ่มเงินเดือนให้กับผู้ที่ต้องใช้ที่จอดรถ (car_park=True) จำนวน 1000 บาท

In [25]:
df.loc[df["car_park"] == True, "salary"] += 1000
df

,eid,name,gender,department,age,height,weight,gpa,salary,working_years,car_park,birth_place,bmi
0,E011,Anda,female,developer,39,166,53.8,3.02,65200.0,4,True,Bangkok,19.523879
1,E012,Bordin,male,developer,25,179,78.4,2.39,49700.0,2,True,Phuket,24.468650
2,E013,Chantana,female,developer,29,171,70.2,3.02,45500.0,3,False,Chonburi,24.007387
3,E014,Donlaya,female,marketing,39,154,66.5,3.21,72600.0,8,False,Chonburi,28.040142
4,E015,Ekkasit,male,marketing,37,177,66.4,3.33,89550.0,7,True,Suphanburi,21.194421
5,E016,Fundee,female,support,35,156,75.6,2.38,56600.0,3,False,Phuket,31.065089
6,E017,Gitiwit,male,support,26,175,69.7,3.25,42400.0,2,False,Suphanburi,22.759184
7,E018,Harit,male,devops,32,180,67.5,3.45,68700.0,5,True,Bangkok,20.833333

## Q6

Show the average GPA grouped by department.

จงแสดงค่าเฉลี่ย GPA ตามแผนก

In [29]:
df.groupby("department")["gpa"].mean()

department
developer    2.810
devops       3.450
marketing    3.270
support      2.815
Name: gpa, dtype: float64

## Q7

Show the average age of female in each department.

จงหาค่าเฉลี่ยอายุของผู้หญิงในแต่ละแผนก

In [31]:
df[df["gender"] == "female"].groupby("department")["age"].mean()

department
developer    34.0
marketing    39.0
support      35.0
Name: age, dtype: float64

## Q8

Show the average age, maximum GPA, minimum GPA, and number of people in each department.

จงแสดง อายุเฉลี่ย, GPA สูงสุด, GPA ต่ำสุด, และจำนวนของพนักงาน ในแต่ละแผนก

In [34]:
df.groupby("department").agg({"age":"mean", "gpa":["max", "min"], "department":"count"})

             age   gpa       department
            mean   max   min      count
department
developer   31.0  3.02  2.39          3
devops      32.0  3.45  3.45          1
marketing   38.0  3.33  3.21          2
support     30.5  3.25  2.38          2

## Q9

Create a new column named "weight_lbs", and
use a lambda function to calculate the weight (in kg) into lbs.


จำสร้างคอลัมน์ใหม่ชื่อ "weight_lbs" ทีใช้ lambda function เพื่อแปลงน้ำหนักจาก กิโลกรัม เป็นหน่วย ปอนด์

In [36]:
df["weight_lbs"] = df["weight"].apply(lambda x: x * 2.205)
df

,eid,name,gender,department,age,height,weight,gpa,salary,working_years,car_park,birth_place,bmi,weight_lbs
0,E011,Anda,female,developer,39,166,53.8,3.02,65200.0,4,True,Bangkok,19.523879,118.6290
1,E012,Bordin,male,developer,25,179,78.4,2.39,49700.0,2,True,Phuket,24.468650,172.8720
2,E013,Chantana,female,developer,29,171,70.2,3.02,45500.0,3,False,Chonburi,24.007387,154.7910
3,E014,Donlaya,female,marketing,39,154,66.5,3.21,72600.0,8,False,Chonburi,28.040142,146.6325
4,E015,Ekkasit,male,marketing,37,177,66.4,3.33,89550.0,7,True,Suphanburi,21.194421,146.4120
5,E016,Fundee,female,support,35,156,75.6,2.38,56600.0,3,False,Phuket,31.065089,166.6980
6,E017,Gitiwit,male,support,26,175,69.7,3.25,42400.0,2,False,Suphanburi,22.759184,153.6885
7,E018,Harit,male,devops,32,180,67.5,3.45,68700.0,5,True,Bangkok,20.833333,148.8375

## Q10

Create a new column named "bmi_lambda", and use a lambda function to calculate the BMI.

จงสร้างคอลัมน์ใหม่ชื่อ "bmi_lambda" โดยใช้ lambda function คำนวณค่า BMI

In [37]:
df["bmi_lambda"] = df.apply(lambda row: row["weight"] / (row["height"] / 100) ** 2, axis=1)
df

,eid,name,gender,department,age,height,weight,gpa,salary,working_years,car_park,birth_place,bmi,weight_lbs,bmi_lambda
0,E011,Anda,female,developer,39,166,53.8,3.02,65200.0,4,True,Bangkok,19.523879,118.6290,19.523879
1,E012,Bordin,male,developer,25,179,78.4,2.39,49700.0,2,True,Phuket,24.468650,172.8720,24.468650
2,E013,Chantana,female,developer,29,171,70.2,3.02,45500.0,3,False,Chonburi,24.007387,154.7910,24.007387
3,E014,Donlaya,female,marketing,39,154,66.5,3.21,72600.0,8,False,Chonburi,28.040142,146.6325,28.040142
4,E015,Ekkasit,male,marketing,37,177,66.4,3.33,89550.0,7,True,Suphanburi,21.194421,146.4120,21.194421
5,E016,Fundee,female,support,35,156,75.6,2.38,56600.0,3,False,Phuket,31.065089,166.6980,31.065089
6,E017,Gitiwit,male,support,26,175,69.7,3.25,42400.0,2,False,Suphanburi,22.759184,153.6885,22.759184
7,E018,Harit,male,devops,32,180,67.5,3.45,68700.0,5,True,Bangkok,20.833333,148.8375,20.833333



---
https://rathachai.creatier.pro/

## つづく