<a href="https://colab.research.google.com/github/mindchu/01276551-INTRO-TO-DATA-ANALYTICS/blob/main/quiz/pandas_quiz_ep1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#@title Your Information

full_name =  'Chuthathip Termchaikul' #@param {type:"string"}
student_id =  '67011594'  #@param {type:"string"}

#@markdown ---

# **Pandas Quiz Ep.1**
> ## *Author* : [Rathachai CHAWUTHAI](https://rathachai.creatier.pro/) , Ph.D
> ### *Affiliation* : Computer Engineering, King Mongkut's Institute of Technology Ladkrabang (KMITL)
> #### *Updated Date* : 2022-03-23
---

## Instruction

Write Python code to answer each question. You must use 1 line of code for each answer.

## คำสั่ง

จงเขียนโค้ดภาษาไพธอนเพื่อตอบคำถาม
โดยเขียนคำตอบด้วยโค้ด 1 บรรทัดโค้ดเท่านั้น

## Q0

Import nessessary Libraries

นำเข้า libraries ที่จำเป็น

In [2]:
import pandas as pd

## Q1

Read data from
https://docs.google.com/spreadsheets/d/e/2PACX-1vRIFbIywXecgxN5c1sMn_KYWsARoXgp4paFxu4qndPaX_47vRaOdrqmiHjtNZ9ZYQcv3ubMSv8DA9ta/pub?gid=0&single=true&output=csv  

into a dataframe named **df**

จงอ่านข้อมูลจาก sheet จาก link ที่กำหนดเป็น Pandas Dataframe ชื่อ **df**

In [20]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRIFbIywXecgxN5c1sMn_KYWsARoXgp4paFxu4qndPaX_47vRaOdrqmiHjtNZ9ZYQcv3ubMSv8DA9ta/pub?gid=0&single=true&output=csv")

## Q2

Display the whole dataframe.

จงแสดงข้อมูลทั้งตาราง

In [4]:
df

,eid,name,gender,department,age,height,weight,gpa,salary,working_years,car_park,birth_place
0,E011,Anda,female,developer,39,166,53.8,3.02,64200.0,4,True,Bangkok
1,E012,Bordin,male,developer,25,179,78.4,2.39,48700.0,2,True,Phuket
2,E013,Chantana,female,developer,29,171,70.2,3.02,45500.0,3,False,Chonburi
3,E014,Donlaya,female,marketing,39,154,66.5,3.21,72600.0,8,False,Chonburi
4,E015,Ekkasit,male,marketing,37,177,66.4,3.33,80500.0,7,True,Suphanburi
5,E016,Fundee,female,support,35,156,75.6,2.38,56600.0,3,False,Phuket
6,E017,Gitiwit,male,support,26,175,69.7,3.25,42400.0,2,False,Suphanburi
7,E018,Harit,male,devops,32,180,67.5,3.45,67700.0,5,True,Bangkok

## Q3

Display the first 3 rows of the dataframe.

จงแสดงข้อมูล 3 บรรทัดแรกของตาราง

In [8]:
df.head(3)

,eid,name,gender,department,age,height,weight,gpa,salary,working_years,car_park,birth_place
0,E011,Anda,female,developer,39,166,53.8,3.02,64200.0,4,True,Bangkok
1,E012,Bordin,male,developer,25,179,78.4,2.39,48700.0,2,True,Phuket
2,E013,Chantana,female,developer,29,171,70.2,3.02,45500.0,3,False,Chonburi

## Q4

Display the last 3 rows of the dataframe.

จงแสดงข้อมูล 3 บรรทัดสุดท้ายของตาราง

In [9]:
df.tail(3)

,eid,name,gender,department,age,height,weight,gpa,salary,working_years,car_park,birth_place
5,E016,Fundee,female,support,35,156,75.6,2.38,56600.0,3,False,Phuket
6,E017,Gitiwit,male,support,26,175,69.7,3.25,42400.0,2,False,Suphanburi
7,E018,Harit,male,devops,32,180,67.5,3.45,67700.0,5,True,Bangkok

## Q5

Display data only columns: name, gender, and birth_place.

จงแสดงข้อมูลเฉพาะคอลัมน์ name, gender, และ birth_place

In [11]:
df[["name", "gender", "birth_place"]]

       name  gender birth_place
0      Anda  female     Bangkok
1    Bordin    male      Phuket
2  Chantana  female    Chonburi
3   Donlaya  female    Chonburi
4   Ekkasit    male  Suphanburi
5    Fundee  female      Phuket
6   Gitiwit    male  Suphanburi
7     Harit    male     Bangkok

## Q6

Display data only the rows of Bordin, Fundee, and Harit.

จงแสดงข้อมูลเฉพาะแถวของ Bordin, Fundee, และ Harit

In [14]:
df[df['name'].isin(['Bordin', 'Fundee', 'Harit'])]

,eid,name,gender,department,age,height,weight,gpa,salary,working_years,car_park,birth_place
1,E012,Bordin,male,developer,25,179,78.4,2.39,48700.0,2,True,Phuket
5,E016,Fundee,female,support,35,156,75.6,2.38,56600.0,3,False,Phuket
7,E018,Harit,male,devops,32,180,67.5,3.45,67700.0,5,True,Bangkok

## Q7

Display the name and salary of employee IDs E014 and E017.

จงแสดงเฉพาะ name และ salary ของพนักงานรหัส  E014 กับ E017

In [28]:
df.loc[df['eid'].isin(['E014', 'E017']), ['name', 'salary']]

      name   salary
3  Donlaya  72600.0
6  Gitiwit  42400.0

## Q8

Display only rows of ones who have a car park space.

จงแสดงข้อมูลทั้งแถวเฉพาะผู้ที่ใช้ที่จอดรถ

In [22]:
df[df['car_park'] == True]

,eid,name,gender,department,age,height,weight,gpa,salary,working_years,car_park,birth_place
0,E011,Anda,female,developer,39,166,53.8,3.02,64200.0,4,True,Bangkok
1,E012,Bordin,male,developer,25,179,78.4,2.39,48700.0,2,True,Phuket
4,E015,Ekkasit,male,marketing,37,177,66.4,3.33,80500.0,7,True,Suphanburi
7,E018,Harit,male,devops,32,180,67.5,3.45,67700.0,5,True,Bangkok

## Q9

Display "name" of only womens having a car park space.

จงแสดง "ชื่อ" ของผู้ที่ใช้ที่จอดรถ และเป็นผู้หญิง

In [27]:
df.loc[(df['gender'] == 'female') & (df['car_park'] == True), "name"]

0    Anda
Name: name, dtype: object

## Q10

Display the salary of Ekkasit.

จงแสดงเงินเดือนของ Ekkasit

In [25]:
df[df['name'] == 'Ekkasit']['salary']

4    80500.0
Name: salary, dtype: float64

In [26]:
df.loc[df["name"] == "Ekkasit", "salary"]

4    80500.0
Name: salary, dtype: float64



---
https://rathachai.creatier.pro/

## つづく